# Generated by Django 4.1.6 on 2023-02-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('json', models.CharField(max_length=10000)),
                ('xml', models.CharField(max_length=10000)),
            ],
        ),
    ]
