# Generated by Django 4.1.6 on 2023-02-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCPDWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
