# Generated by Django 4.1.6 on 2023-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCPDWeb', '0002_alter_pattern_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='desc',
            field=models.CharField(default='Quantum Circuit Design Pattern', max_length=1000),
        ),
    ]
