# Generated by Django 4.1.6 on 2023-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QCPDWeb', '0003_pattern_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='url',
            field=models.CharField(default='https://www.quantumcomputingpatterns.org/#/', max_length=1000),
        ),
    ]
